# -*- coding: utf-8 -*-
"""
arasCore/lib/server_config.py
Server configuration manager — read/write instance/server.json
and generate gunicorn.conf.py on save.
"""
import os
import json
import logging

logger = logging.getLogger(__name__)

_DEFAULTS = {
    "wsgi_server":  "gunicorn",   # gunicorn | uwsgi | flask
    "host":         "0.0.0.0",
    "port":         8080,
    "workers":      2,
    "threads":      2,
    "worker_class": "sync",       # sync | gevent | gthread
    "timeout":      30,
    "keepalive":    2,
    "max_requests": 1000,
    "ssl_enabled":  False,
    "ssl_certfile": "",
    "ssl_keyfile":  "",
    "loglevel":     "info",       # debug | info | warning | error
    "accesslog":    "-",          # - = stdout
    "errorlog":     "-",
}


def _config_path(flask_app):
    return os.path.join(flask_app.instance_path, "server.json")


def load(flask_app) -> dict:
    path = _config_path(flask_app)
    cfg  = dict(_DEFAULTS)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                cfg.update(json.load(f))
        except Exception as e:
            logger.warning(f"[server_config] load error: {e}")
    return cfg


def save(flask_app, data: dict) -> dict:
    """Validate, save server.json, and regenerate gunicorn.conf.py."""
    cfg = dict(_DEFAULTS)
    cfg.update({k: v for k, v in data.items() if k in _DEFAULTS})

    # Type coercions
    cfg["port"]         = int(cfg["port"])
    cfg["workers"]      = max(1, int(cfg["workers"]))
    cfg["threads"]      = max(1, int(cfg["threads"]))
    cfg["timeout"]      = max(1, int(cfg["timeout"]))
    cfg["keepalive"]    = max(0, int(cfg["keepalive"]))
    cfg["max_requests"] = max(0, int(cfg["max_requests"]))
    cfg["ssl_enabled"]  = bool(cfg["ssl_enabled"])

    os.makedirs(flask_app.instance_path, exist_ok=True)
    path = _config_path(flask_app)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
    logger.info(f"[server_config] saved to {path}")

    _write_gunicorn_conf(flask_app, cfg)
    return cfg


def _write_gunicorn_conf(flask_app, cfg: dict):
    """Generate gunicorn.conf.py at project root."""
    project_root = os.path.dirname(flask_app.root_path)
    out = os.path.join(project_root, "gunicorn.conf.py")

    bind = f"{cfg['host']}:{cfg['port']}"
    ssl_lines = ""
    if cfg.get("ssl_enabled") and cfg.get("ssl_certfile"):
        ssl_lines = (
            f'\ncertfile = "{cfg["ssl_certfile"]}"\n'
            f'keyfile  = "{cfg["ssl_keyfile"]}"\n'
        )

    content = f"""# Auto-generated by Aras Server Settings — do not edit manually.
bind         = "{bind}"
workers      = {cfg['workers']}
threads      = {cfg['threads']}
worker_class = "{cfg['worker_class']}"
timeout      = {cfg['timeout']}
keepalive    = {cfg['keepalive']}
max_requests = {cfg['max_requests']}
loglevel     = "{cfg['loglevel']}"
accesslog    = "{cfg['accesslog']}"
errorlog     = "{cfg['errorlog']}"{ssl_lines}
"""
    with open(out, "w", encoding="utf-8") as f:
        f.write(content)
    logger.info(f"[server_config] gunicorn.conf.py written to {out}")


def restart_server():
    """Send SIGHUP to reload workers (gunicorn) or exit (dev server)."""
    import os, signal
    os.kill(os.getpid(), signal.SIGHUP)
