version: "3.8"

services:
  app:
    build: .
    container_name: aras_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: host.docker.internal
      DB_USER: root
      DB_PASSWORD: "999999"
      DB_NAME: arasdev
      DB_PORT: 3306
      SQLALCHEMY_DATABASE_URI: mariadb+mariadbconnector://root:999999@host.docker.internal:3306/arasdev
      DB_URI: mariadb+mariadbconnector://root:999999@host.docker.internal:3306/arasdev
      FLASK_RUN_PORT: 8080
      SECRET_KEY: ${SECRET_KEY:-your_secret_key_here}
      FLASK_ENV: development
    volumes:
      - .:/app # Mount the current directory into the container for live updates (optional but useful for dev)
    command: sh -c "python wait_for_db.py && flask aras dbca && flask aras erp-init && python run.py"
