# Auto-generated by Aras Server Settings — do not edit manually.
bind         = "0.0.0.0:8080"
workers      = 2
threads      = 2
worker_class = "sync"
timeout      = 30
keepalive    = 2
max_requests = 1000
loglevel     = "info"
accesslog    = "-"
errorlog     = "-"
