[metadata]
name = aras
version = 0.2.0
maintainer = aras
description = Aras Framework.

[options]
packages = find: 
package_dir =
include_package_data = True 
install_requires =
    alembic
    amqp
    aniso8601
    astroid
    attrs
    autopep8
    backports.entry-points-selectable
    bcrypt
    billiard
    black
    blinker
    build
    celery
    certifi
    cffi
    chardet
    charset-normalizer
    click
    click-didyoumean
    click-plugins
    click-repl
    coverage
    decorator
    defusedxml
    distlib
    dnspython
    email-validator
    Faker
    filelock
    Flask
    Flask-Bcrypt
    Flask-Caching
    Flask-DebugToolbar
    Flask-Login
    Flask-Mail
    flask-marshmallow
    Flask-RESTful
    Flask-Script
    Flask-SQLAlchemy
    Flask-WTF
    ForgeryPy
    greenlet
    httpie
    idna
    infinity
    iniconfig
    intervals
    isort
    itsdangerous
    Jinja2
    kombu
    lazy-object-proxy
    Mako
    mariadb
    MarkupSafe
    marshmallow
    marshmallow-sqlalchemy
    mccabe
    mypy-extensions
    numpy
    packaging
    # pandas
    pathspec
    pep517
    platformdirs
    pluggy
    prompt-toolkit
    py
    pycodestyle
    pycparser
    Pygments
    PyMySQL
    pyparsing
    PySocks
    pytest
    python-dateutil
    pytz
    raven
    requests
    requests-toolbelt
    sentry-sdk
    six
    SQLAlchemy
    SQLAlchemy-Utils
    text-unidecode
    toml
    tomli
    typing_extensions
    urllib3
    validators
    vine
    virtualenv
    wcwidth
    Werkzeug
    wrapt
    WTForms
    WTForms-Alchemy
    WTForms-Components
    yapf

[options.packages.find]
where = aras
include = app_*, lib, static, templates
exclude = 

[options.extras_require]
test = 
    pytest

[options.entry_points]
console_scripts =
    testcmd = aras.lib:cli

[tool:pytest]
python_files = test_*.py
testpaths = tests

[coverage:run]
branch = True
source = 
    aras
