import { registerCustomPage } from '../../aras-core/customPageRegistry'

registerCustomPage('dev.overview', () => import('./OverviewTab'))
registerCustomPage('dev.schema', () => import('./SchemaTab'))
registerCustomPage('dev.models', () => import('./ModelRegistry'))
registerCustomPage('dev.routes', () => import('./RouteDebugger'))
registerCustomPage('dev.timeline', () => import('./RequestTimeline'))
registerCustomPage('dev.workbench', () => import('./WorkbenchTab'))
registerCustomPage('dev.cache', () => import('./CacheControl'))
registerCustomPage('dev.commands', () => import('./DevCommandPalette'))
registerCustomPage('dev.sql', () => import('./SqlRunner'))
registerCustomPage('dev.access', () => import('./AccessTab'))
registerCustomPage('dev.testlab', () => import('./ApiConsole'))
registerCustomPage('dev.scaffold', () => import('./ScaffoldTab'))
registerCustomPage('dev.mocks', () => import('./MockGallery'))
registerCustomPage('dev.apihelp', () => import('./ApiHelpTab'))
registerCustomPage('dev.handoff', () => import('./HandoffTab'))
registerCustomPage('dev.logs', () => import('./LogStream'))
registerCustomPage('dev.templatebuilder', () => import('../TemplateBuilder'))
registerCustomPage('dev.help', () => import('../HelpDev'))
