import type { SerializedNode, SerializedNodes } from '@craftjs/core'
import { createResponsiveBoxSettings, createResponsiveColumns } from './breakpoints'

const defaultCustom = {
  note: '',
  locked: false,
  noteStatus: 'pending',
}

function createNode(
  type: string,
  props: Record<string, unknown>,
  parent: string | null,
  nodes: string[] = [],
  isCanvas = false,
): SerializedNode {
  return {
    type: { resolvedName: type },
    isCanvas,
    props,
    displayName: type,
    parent,
    nodes,
    linkedNodes: {},
    hidden: false,
    custom: { ...defaultCustom },
  }
}

export const DEFAULT_TEMPLATE_NAME = 'erp-modern-invoice'

export const defaultTree: SerializedNodes = {
  ROOT: createNode(
    'Box',
    {
      label: 'Invoice Canvas',
      as: 'div',
      fill: false,
      minHeight: 980,
      hiddenOverflow: false,
      className: 'template-studio-dot-grid w-full',
      settings: createResponsiveBoxSettings({
        desktop: {
          direction: 'row',
          align: 'stretch',
          justify: 'start',
          padding: { top: 24, right: 24, bottom: 24, left: 24 },
          gap: 24,
          radius: 0,
          bg: 'transparent',
        },
        tablet: {
          direction: 'row',
          align: 'stretch',
          justify: 'start',
          padding: { top: 24, right: 24, bottom: 24, left: 24 },
          gap: 24,
          radius: 0,
          bg: 'transparent',
        },
        mobile: {
          direction: 'row',
          align: 'stretch',
          justify: 'start',
          padding: { top: 16, right: 16, bottom: 16, left: 16 },
          gap: 16,
          radius: 0,
          bg: 'transparent',
        },
      }),
    },
    null,
    ['sidebar', 'main'],
    true,
  ),
  sidebar: createNode(
    'Sidebar',
    {
      label: 'Sidebar',
      brand: 'Nexus',
      bg: 'rgba(255, 255, 255, 0.85)',
      width: { desktop: 256, tablet: 80, mobile: 80 },
      items: [
        { label: 'Dashboard', icon: 'layout-grid', active: false },
        { label: 'Invoice Form', icon: 'file-text', active: true },
      ],
      userName: 'A. Aras',
      userRole: '',
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: {
          padding: { top: 16, right: 16, bottom: 16, left: 16 },
          gap: 0,
          radius: 24,
          bg: 'rgba(255, 255, 255, 0.85)',
        },
        tablet: {
          padding: { top: 16, right: 12, bottom: 16, left: 12 },
          gap: 0,
          radius: 24,
          bg: 'rgba(255, 255, 255, 0.85)',
        },
        mobile: {
          padding: { top: 16, right: 12, bottom: 16, left: 12 },
          gap: 0,
          radius: 24,
          bg: 'rgba(255, 255, 255, 0.85)',
        },
      }),
    },
    'ROOT',
    [],
    true,
  ),
  main: createNode(
    'Box',
    {
      label: 'Main',
      as: 'main',
      fill: true,
      minHeight: null,
      hiddenOverflow: false,
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: {
          direction: 'col',
          align: 'stretch',
          justify: 'start',
          gap: 24,
        },
        tablet: {
          direction: 'col',
          align: 'stretch',
          justify: 'start',
          gap: 24,
        },
        mobile: {
          direction: 'col',
          align: 'stretch',
          justify: 'start',
          gap: 16,
        },
      }),
    },
    'ROOT',
    ['header', 'content'],
    true,
  ),
  header: createNode(
    'Header',
    {
      label: 'Header',
      title: 'Invoice',
      recordId: '#INV-24-092',
      subtitle: 'Editing Record',
      primaryLabel: 'Save Record',
      secondaryLabel: 'Cancel',
      primaryVariant: 'primary',
      secondaryVariant: 'ghost',
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: {
          direction: 'row',
          align: 'center',
          justify: 'between',
          padding: { top: 0, right: 24, bottom: 0, left: 24 },
          height: 80,
          gap: 16,
          radius: 24,
        },
        tablet: {
          direction: 'row',
          align: 'center',
          justify: 'between',
          padding: { top: 0, right: 20, bottom: 0, left: 20 },
          height: 80,
          gap: 16,
          radius: 24,
        },
        mobile: {
          direction: 'col',
          align: 'stretch',
          justify: 'center',
          padding: { top: 18, right: 18, bottom: 18, left: 18 },
          height: null,
          gap: 14,
          radius: 24,
        },
      }),
    },
    'main',
  ),
  content: createNode(
    'Box',
    {
      label: 'Content',
      as: 'div',
      fill: true,
      className: 'template-studio-hide-scroll overflow-y-auto pb-6',
      minHeight: null,
      hiddenOverflow: false,
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'row', gap: 24, align: 'start' },
        tablet: { direction: 'row', gap: 20, align: 'start' },
        mobile: { direction: 'col', gap: 16, align: 'stretch' },
      }),
    },
    'main',
    ['leftColumn', 'rightColumn'],
    true,
  ),
  leftColumn: createNode(
    'Box',
    {
      label: 'Left Column',
      fill: true,
      className: '',
      minHeight: null,
      hiddenOverflow: false,
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'col', gap: 24, align: 'stretch' },
        tablet: { direction: 'col', gap: 20, align: 'stretch' },
        mobile: { direction: 'col', gap: 16, align: 'stretch' },
      }),
    },
    'content',
    ['clientIsland', 'billingIsland', 'lineItemsIsland'],
    true,
  ),
  rightColumn: createNode(
    'Box',
    {
      label: 'Right Column',
      fill: false,
      className: '',
      minHeight: null,
      hiddenOverflow: false,
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'col', gap: 24, align: 'stretch', width: 352 },
        tablet: { direction: 'col', gap: 20, align: 'stretch', width: 300 },
        mobile: { direction: 'col', gap: 16, align: 'stretch', width: null },
      }),
    },
    'content',
    ['summaryIsland', 'statusIsland'],
    true,
  ),
  clientIsland: createNode(
    'Island',
    {
      label: 'Client Details',
      variant: 'light',
      title: 'Client Details',
      titleStyle: 'section',
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 16, radius: 24, bg: 'transparent' },
        tablet: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 16, radius: 24, bg: 'transparent' },
        mobile: { padding: { top: 20, right: 20, bottom: 20, left: 20 }, gap: 14, radius: 24, bg: 'transparent' },
      }),
    },
    'leftColumn',
    ['clientGrid'],
    true,
  ),
  clientGrid: createNode(
    'FieldGrid',
    {
      label: 'Client Grid',
      className: '',
      cols: createResponsiveColumns(2, 2, 1),
      settings: createResponsiveBoxSettings({
        desktop: { gap: 16 },
        tablet: { gap: 16 },
        mobile: { gap: 12 },
      }),
    },
    'clientIsland',
    ['customerField', 'emailField'],
    true,
  ),
  customerField: createNode(
    'Field',
    {
      label: 'Customer Name',
      value: 'Acme Corporation',
      placeholder: 'Select customer',
      type: 'select',
      fullWidth: false,
    },
    'clientGrid',
  ),
  emailField: createNode(
    'Field',
    {
      label: 'Contact Email',
      value: 'billing@acme.corp',
      placeholder: 'name@company.com',
      type: 'input',
      fullWidth: false,
    },
    'clientGrid',
  ),
  billingIsland: createNode(
    'Island',
    {
      label: 'Billing Information',
      variant: 'light',
      title: 'Billing Information',
      titleStyle: 'section',
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 16, radius: 24, bg: 'transparent' },
        tablet: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 16, radius: 24, bg: 'transparent' },
        mobile: { padding: { top: 20, right: 20, bottom: 20, left: 20 }, gap: 14, radius: 24, bg: 'transparent' },
      }),
    },
    'leftColumn',
    ['billingGrid'],
    true,
  ),
  billingGrid: createNode(
    'FieldGrid',
    {
      label: 'Billing Grid',
      className: '',
      cols: createResponsiveColumns(2, 2, 1),
      settings: createResponsiveBoxSettings({
        desktop: { gap: 16 },
        tablet: { gap: 16 },
        mobile: { gap: 12 },
      }),
    },
    'billingIsland',
    ['issueDateField', 'dueDateField', 'addressField'],
    true,
  ),
  issueDateField: createNode(
    'Field',
    {
      label: 'Issue Date',
      value: '2024-10-24',
      placeholder: '',
      type: 'date',
      fullWidth: false,
    },
    'billingGrid',
  ),
  dueDateField: createNode(
    'Field',
    {
      label: 'Due Date',
      value: '2024-11-24',
      placeholder: '',
      type: 'date',
      fullWidth: false,
    },
    'billingGrid',
  ),
  addressField: createNode(
    'Field',
    {
      label: 'Billing Address',
      value: '123 Innovation Drive\nSan Francisco, CA 94105',
      placeholder: '',
      type: 'textarea',
      fullWidth: true,
    },
    'billingGrid',
  ),
  lineItemsIsland: createNode(
    'Island',
    {
      label: 'Line Items',
      variant: 'light',
      title: '',
      titleStyle: 'section',
      className: 'p-0',
      settings: createResponsiveBoxSettings({
        desktop: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, gap: 0, radius: 24, bg: 'transparent' },
        tablet: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, gap: 0, radius: 24, bg: 'transparent' },
        mobile: { padding: { top: 0, right: 0, bottom: 0, left: 0 }, gap: 0, radius: 24, bg: 'transparent' },
      }),
    },
    'leftColumn',
    ['lineItemsShell'],
    true,
  ),
  lineItemsShell: createNode(
    'Box',
    {
      label: 'Line Items Shell',
      fill: true,
      hiddenOverflow: false,
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'col', gap: 0 },
        tablet: { direction: 'col', gap: 0 },
        mobile: { direction: 'col', gap: 0 },
      }),
    },
    'lineItemsIsland',
    ['lineItemsHeader', 'lineItemsTable'],
    true,
  ),
  lineItemsHeader: createNode(
    'Box',
    {
      label: 'Line Items Header',
      fill: true,
      hiddenOverflow: false,
      className: 'border-b border-[rgba(226,232,240,0.55)] bg-white/40',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'row', align: 'center', justify: 'between', padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 12 },
        tablet: { direction: 'row', align: 'center', justify: 'between', padding: { top: 20, right: 20, bottom: 20, left: 20 }, gap: 12 },
        mobile: { direction: 'col', align: 'stretch', justify: 'start', padding: { top: 18, right: 18, bottom: 18, left: 18 }, gap: 10 },
      }),
    },
    'lineItemsShell',
    ['lineItemsTitle', 'lineItemsAction'],
    true,
  ),
  lineItemsTitle: createNode(
    'Text',
    {
      text: 'Line Items',
      variant: 'heading',
      className: '',
    },
    'lineItemsHeader',
  ),
  lineItemsAction: createNode(
    'ButtonEl',
    {
      label: 'Add Row',
      variant: 'ghost',
      icon: 'plus',
      className: 'border-transparent bg-transparent px-0 text-[var(--ts-brand-600)] shadow-none hover:bg-transparent',
    },
    'lineItemsHeader',
  ),
  lineItemsTable: createNode(
    'Box',
    {
      label: 'Line Items Table',
      fill: true,
      hiddenOverflow: false,
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'col', gap: 0 },
        tablet: { direction: 'col', gap: 0 },
        mobile: { direction: 'col', gap: 0 },
      }),
    },
    'lineItemsShell',
    ['lineItemsHead', 'lineItemRow1', 'lineItemRow2'],
    true,
  ),
  lineItemsHead: createNode(
    'Box',
    {
      label: 'Line Items Table Head',
      fill: true,
      hiddenOverflow: false,
      className: 'border-b border-[rgba(226,232,240,0.55)] bg-[rgba(248,250,252,0.7)]',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'row', align: 'center', justify: 'start', padding: { top: 12, right: 24, bottom: 12, left: 24 }, gap: 16 },
        tablet: { direction: 'row', align: 'center', justify: 'start', padding: { top: 12, right: 20, bottom: 12, left: 20 }, gap: 12 },
        mobile: { direction: 'row', align: 'center', justify: 'start', padding: { top: 10, right: 14, bottom: 10, left: 14 }, gap: 8 },
      }),
    },
    'lineItemsTable',
    ['lineHeadDesc', 'lineHeadQty', 'lineHeadPrice', 'lineHeadTotal'],
    true,
  ),
  lineHeadDesc: createNode(
    'Text',
    {
      text: 'Description',
      variant: 'label',
      className: 'flex-1',
    },
    'lineItemsHead',
  ),
  lineHeadQty: createNode(
    'Text',
    {
      text: 'Qty',
      variant: 'label',
      className: 'w-20',
    },
    'lineItemsHead',
  ),
  lineHeadPrice: createNode(
    'Text',
    {
      text: 'Price',
      variant: 'label',
      className: 'w-28',
    },
    'lineItemsHead',
  ),
  lineHeadTotal: createNode(
    'Text',
    {
      text: 'Total',
      variant: 'label',
      className: 'w-28 text-right',
    },
    'lineItemsHead',
  ),
  lineItemRow1: createNode(
    'Box',
    {
      label: 'Line Item Row 1',
      fill: true,
      hiddenOverflow: false,
      className: 'border-b border-[rgba(241,245,249,0.85)] bg-white/20',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'row', align: 'center', padding: { top: 12, right: 24, bottom: 12, left: 24 }, gap: 16 },
        tablet: { direction: 'row', align: 'center', padding: { top: 12, right: 20, bottom: 12, left: 20 }, gap: 12 },
        mobile: { direction: 'col', align: 'stretch', padding: { top: 12, right: 14, bottom: 12, left: 14 }, gap: 10 },
      }),
    },
    'lineItemsTable',
    ['lineItemDesc1', 'lineItemQty1', 'lineItemPrice1', 'lineItemTotal1'],
    true,
  ),
  lineItemDesc1: createNode(
    'Field',
    {
      label: '',
      value: 'Enterprise Software License',
      placeholder: '',
      type: 'input',
      fullWidth: false,
    },
    'lineItemRow1',
  ),
  lineItemQty1: createNode(
    'Field',
    {
      label: '',
      value: '1',
      placeholder: '',
      type: 'input',
      fullWidth: false,
    },
    'lineItemRow1',
  ),
  lineItemPrice1: createNode(
    'Field',
    {
      label: '',
      value: '$3,500.00',
      placeholder: '',
      type: 'input',
      fullWidth: false,
    },
    'lineItemRow1',
  ),
  lineItemTotal1: createNode(
    'Text',
    {
      text: '$3,500.00',
      variant: 'paragraph',
      className: 'w-28 text-right font-mono font-bold text-[var(--ts-surface-900)]',
    },
    'lineItemRow1',
  ),
  lineItemRow2: createNode(
    'Box',
    {
      label: 'Line Item Row 2',
      fill: true,
      hiddenOverflow: false,
      className: 'bg-white/20',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'row', align: 'center', padding: { top: 12, right: 24, bottom: 12, left: 24 }, gap: 16 },
        tablet: { direction: 'row', align: 'center', padding: { top: 12, right: 20, bottom: 12, left: 20 }, gap: 12 },
        mobile: { direction: 'col', align: 'stretch', padding: { top: 12, right: 14, bottom: 12, left: 14 }, gap: 10 },
      }),
    },
    'lineItemsTable',
    ['lineItemDesc2', 'lineItemQty2', 'lineItemPrice2', 'lineItemTotal2'],
    true,
  ),
  lineItemDesc2: createNode(
    'Field',
    {
      label: '',
      value: 'Implementation Support (Hours)',
      placeholder: '',
      type: 'input',
      fullWidth: false,
    },
    'lineItemRow2',
  ),
  lineItemQty2: createNode(
    'Field',
    {
      label: '',
      value: '5',
      placeholder: '',
      type: 'input',
      fullWidth: false,
    },
    'lineItemRow2',
  ),
  lineItemPrice2: createNode(
    'Field',
    {
      label: '',
      value: '$140.00',
      placeholder: '',
      type: 'input',
      fullWidth: false,
    },
    'lineItemRow2',
  ),
  lineItemTotal2: createNode(
    'Text',
    {
      text: '$700.00',
      variant: 'paragraph',
      className: 'w-28 text-right font-mono font-bold text-[var(--ts-surface-900)]',
    },
    'lineItemRow2',
  ),
  summaryIsland: createNode(
    'Island',
    {
      label: 'Financial Summary',
      variant: 'dark',
      title: 'Financial Summary',
      titleStyle: 'section',
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 12, radius: 24, bg: 'var(--ts-surface-900)' },
        tablet: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 12, radius: 24, bg: 'var(--ts-surface-900)' },
        mobile: { padding: { top: 20, right: 20, bottom: 20, left: 20 }, gap: 10, radius: 24, bg: 'var(--ts-surface-900)' },
      }),
    },
    'rightColumn',
    ['summaryRow1', 'summaryRow2', 'summaryRow3', 'postInvoiceButton'],
    true,
  ),
  summaryRow1: createNode(
    'SummaryRow',
    {
      label: 'Subtotal',
      value: '$4,200.00',
      accent: false,
    },
    'summaryIsland',
  ),
  summaryRow2: createNode(
    'SummaryRow',
    {
      label: 'Tax (0%)',
      value: '$0.00',
      accent: false,
    },
    'summaryIsland',
  ),
  summaryRow3: createNode(
    'SummaryRow',
    {
      label: 'Total Amount',
      value: '$4,200.00',
      accent: true,
    },
    'summaryIsland',
  ),
  postInvoiceButton: createNode(
    'ButtonEl',
    {
      label: 'Post Invoice',
      variant: 'ghost',
      icon: '',
      className: 'mt-2 w-full border-white/20 bg-white/10 text-white hover:bg-white/20',
    },
    'summaryIsland',
  ),
  statusIsland: createNode(
    'Island',
    {
      label: 'Status',
      variant: 'light',
      title: '',
      titleStyle: 'section',
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 16, radius: 24, bg: 'transparent' },
        tablet: { padding: { top: 24, right: 24, bottom: 24, left: 24 }, gap: 16, radius: 24, bg: 'transparent' },
        mobile: { padding: { top: 20, right: 20, bottom: 20, left: 20 }, gap: 14, radius: 24, bg: 'transparent' },
      }),
    },
    'rightColumn',
    ['statusTitle', 'statusCard'],
    true,
  ),
  statusTitle: createNode(
    'Text',
    {
      text: 'Record Status',
      variant: 'label',
      className: '',
    },
    'statusIsland',
  ),
  statusCard: createNode(
    'Box',
    {
      label: 'Status Card',
      fill: true,
      hiddenOverflow: false,
      className: 'rounded-xl border border-emerald-100 bg-emerald-50',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'row', align: 'center', gap: 12, padding: { top: 12, right: 12, bottom: 12, left: 12 } },
        tablet: { direction: 'row', align: 'center', gap: 12, padding: { top: 12, right: 12, bottom: 12, left: 12 } },
        mobile: { direction: 'row', align: 'center', gap: 12, padding: { top: 12, right: 12, bottom: 12, left: 12 } },
      }),
    },
    'statusIsland',
    ['statusBadge', 'statusCopy'],
    true,
  ),
  statusBadge: createNode(
    'Box',
    {
      label: 'Status Badge',
      fill: false,
      hiddenOverflow: false,
      className: 'rounded-full bg-emerald-100',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'row', align: 'center', justify: 'center', width: 32, height: 32, radius: 999, bg: 'rgba(209,250,229,1)' },
        tablet: { direction: 'row', align: 'center', justify: 'center', width: 32, height: 32, radius: 999, bg: 'rgba(209,250,229,1)' },
        mobile: { direction: 'row', align: 'center', justify: 'center', width: 32, height: 32, radius: 999, bg: 'rgba(209,250,229,1)' },
      }),
    },
    'statusCard',
    ['statusBadgeText'],
    true,
  ),
  statusBadgeText: createNode(
    'Text',
    {
      text: '✓',
      variant: 'paragraph',
      className: 'text-center text-sm font-bold text-emerald-600',
    },
    'statusBadge',
  ),
  statusCopy: createNode(
    'Box',
    {
      label: 'Status Copy',
      fill: true,
      hiddenOverflow: false,
      className: '',
      settings: createResponsiveBoxSettings({
        desktop: { direction: 'col', gap: 2 },
        tablet: { direction: 'col', gap: 2 },
        mobile: { direction: 'col', gap: 2 },
      }),
    },
    'statusCard',
    ['statusHeading', 'statusMeta'],
    true,
  ),
  statusHeading: createNode(
    'Text',
    {
      text: 'Draft Saved',
      variant: 'paragraph',
      className: 'text-sm font-bold text-emerald-800',
    },
    'statusCopy',
  ),
  statusMeta: createNode(
    'Text',
    {
      text: 'Just now',
      variant: 'paragraph',
      className: 'text-xs font-medium text-emerald-600',
    },
    'statusCopy',
  ),
}

export function cloneDefaultTree() {
  return structuredClone(defaultTree)
}

export default defaultTree
