"""
Purpose: App Installer service for the Aras Framework.
Context: Level 3 Implementation.
Impact: Handles folder scaffolding, YAML/JSON parsing, and Python code generation for new apps.
"""
import os
import yaml
import json
import logging
import textwrap
from typing import Dict, List, Any, Optional
from sqlalchemy.orm import Session
from ..registry.app_model import AppModel
from ..registry.resource_model import ResourceModel
from ..registry.field_model import FieldModel
from ..base.service import Service
from ..lib.helpers import to_label_case

logger = logging.getLogger(__name__)

class AppInstaller(Service):
    """
    Handles the installation and scaffolding of new Aras Applications.
    """

    @staticmethod
    def get_apps_root() -> str:
        # Assuming we are in api/core/lib/installer.py
        # Project root is api/
        # Apps are in api/apps/
        current_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(os.path.dirname(current_dir))
        return os.path.join(project_root, "apps")

    @classmethod
    def create_app_scaffold(cls, app_name: str, definition: Dict[str, Any]) -> str:
        """
        Creates the folder structure and basic Python files for a new app.
        Returns the path to the created app.
        """
        apps_root = cls.get_apps_root()
        app_path = os.path.join(apps_root, app_name)
        
        if os.path.exists(app_path):
            raise ValueError(f"App directory already exists: {app_path}")

        # 1. Create Folders
        os.makedirs(app_path, exist_ok=True)
        # We don't necessarily need templates/static for a headless API framework,
        # but let's follow the old structure if requested.
        os.makedirs(os.path.join(app_path, "migrations"), exist_ok=True)
        
        # 2. Generate Files
        app_data = definition.get("app", {})
        tables_data = definition.get("tables", [])

        files = cls.generate_python_files(app_name, app_data, tables_data)
        
        for filename, content in files.items():
            with open(os.path.join(app_path, filename), "w", encoding="utf-8") as f:
                f.write(content)
        
        # Create empty __init__.py if not present
        if "__init__.py" not in files:
            open(os.path.join(app_path, "__init__.py"), "w").close()

        return app_path

    @classmethod
    def generate_python_files(cls, app_name: str, app_data: Dict[str, Any], tables_data: List[Dict[str, Any]]) -> Dict[str, str]:
        """
        Generates the content for app.py, models.py, and views.py.
        """
        files = {}

        # ── app.py ────────────────────────────────────────────────────────────
        app_label = app_data.get("label", to_label_case(app_name))
        description = app_data.get("description", "")
        icon = app_data.get("icon", "Package")
        version = app_data.get("version", "1.0.0")

        model_classes = [cls._to_camel_case(t["name"]) for t in tables_data]
        imports_str = ", ".join(model_classes)

        app_content = textwrap.dedent(f"""\
            \"\"\"
            App manifest for {app_label}
            Generated by Aras Installer.
            \"\"\"
            from ..aras import Aras
            from .models import {imports_str}
            from . import views

            class {cls._to_camel_case(app_name)}(Aras.App):
                app_name = "{app_name}"
                app_label = "{app_label}"
                description = "{description}"
                icon = "{icon}"
                version = "{version}"
                
                models = [{imports_str}]
        """)
        files["app.py"] = app_content

        # ── models.py ─────────────────────────────────────────────────────────
        model_lines = [
            "from sqlalchemy import Column, String, Integer, Text, Boolean, DateTime, ForeignKey, Float, JSON",
            "from ..aras import Aras",
            "",
        ]

        for tbl in tables_data:
            class_name = cls._to_camel_case(tbl["name"])
            table_name = f"{app_name}_{tbl['name']}"
            
            model_lines += [
                f"class {class_name}(Aras.Model):",
                f"    __tablename__ = \"{table_name}\"",
                "",
            ]

            for col in tbl.get("columns", []):
                col_name = col["name"]
                col_label = col.get("label", to_label_case(col_name))
                col_type = cls._map_field_type(col.get("field_type", "string"))
                required = "nullable=False" if col.get("required") else "nullable=True"
                
                # Check for relations
                if col.get("field_type") == "relation" or "relation_table" in col:
                    target = col.get("relation_table")
                    model_lines.append(f"    {col_name}_id = Column(Integer, ForeignKey(\"{target}.id\"), {required}, info={{\"label\": \"{col_label}\", \"ui_type\": \"lookup\"}})")
                else:
                    model_lines.append(f"    {col_name} = Column({col_type}, {required}, info={{\"label\": \"{col_label}\", \"ui_type\": \"{col.get('field_type', 'string')}\"}})")
            
            model_lines += ["", ""]

        files["models.py"] = "\n".join(model_lines)

        # ── views.py ──────────────────────────────────────────────────────────
        view_lines = [
            "from ..aras import Aras",
            f"from .models import {imports_str}",
            "",
        ]

        for tbl in tables_data:
            class_name = cls._to_camel_case(tbl["name"])
            title = tbl.get("title", to_label_case(tbl["name"]))
            
            view_lines += [
                f"class {class_name}View(Aras.View):",
                f"    model = {class_name}",
                f"    title = \"{title}\"",
                "",
            ]
        
        files["views.py"] = "\n".join(view_lines)

        return files

    @staticmethod
    def _to_camel_case(snake_str: str) -> str:
        return "".join(x.capitalize() for x in snake_str.lower().replace("-", "_").split("_"))

    @staticmethod
    def _map_field_type(field_type: str) -> str:
        mapping = {
            "string": "String(255)",
            "text": "Text",
            "integer": "Integer",
            "float": "Float",
            "boolean": "Boolean",
            "datetime": "DateTime",
            "json": "JSON"
        }
        return mapping.get(field_type, "String(255)")

    @classmethod
    def parse_yaml(cls, yaml_content: str) -> Dict[str, Any]:
        """Parses and validates app YAML definition."""
        try:
            data = yaml.safe_load(yaml_content)
            return cls._validate_definition(data)
        except Exception as e:
            raise ValueError(f"YAML Parse Error: {str(e)}")

    @classmethod
    def parse_json(cls, json_content: str) -> Dict[str, Any]:
        """Parses and validates app JSON definition."""
        try:
            data = json.loads(json_content)
            return cls._validate_definition(data)
        except Exception as e:
            raise ValueError(f"JSON Parse Error: {str(e)}")

    @staticmethod
    def _validate_definition(data: Any) -> Dict[str, Any]:
        from ..base.validation import ManifestDefinition
        try:
            manifest = ManifestDefinition(**data)
            return manifest.model_dump()
        except Exception as e:
            raise ValueError(f"Manifest Validation Error: {str(e)}")

    @classmethod
    def uninstall_app(cls, app_name: str, db: Optional[Session] = None) -> bool:
        """
        Removes an app's directory from the file system.
        If db is provided, it also purges metadata and drops physical tables.
        Returns True if successful, False if the app didn't exist in filesystem.
        """
        if app_name == "dev":
            raise ValueError("The 'dev' application is a core framework component and cannot be uninstalled.")

        import shutil
        apps_root = cls.get_apps_root()
        app_path = os.path.join(apps_root, app_name)
        
        # 1. Clean DB if requested
        if db:
            cls.purge_app_from_db(app_name, db)

        # 2. Clean Filesystem
        if not os.path.exists(app_path):
            return False
            
        shutil.rmtree(app_path)
        logger.info(f"App directory removed: {app_path}")
        return True

    @classmethod
    def purge_app_from_db(cls, app_name: str, db: Session):
        """Removes all traces of an app from the registry and drops its tables."""
        from ..registry.app_model import AppModel
        from ..registry.resource_model import ResourceModel
        from ..registry.field_model import FieldModel
        from ..registry.link_model import LinkModel
        from sqlalchemy import text

        app_db = db.query(AppModel).filter(AppModel.name == app_name).first()
        if not app_db:
            return

        resources = db.query(ResourceModel).filter(ResourceModel.app_id == app_db.id).all()
        resource_ids = [r.id for r in resources]
        table_names = [r.name for r in resources]

        # 1. Drop physical tables (Protect core tables)
        core_tables = {
            "aras_apps", "aras_resources", "aras_fields", "aras_links",
            "translations", "aras_activity_logs", "auth_roles",
            "auth_permissions", "auth_user_roles", "auth_users", "sys_settings"
        }
        for table_name in table_names:
            if table_name in core_tables:
                logger.info(f"Skipping drop for core table: {table_name}")
                continue
            try:
                # Use execute with text for DDL
                db.execute(text(f"DROP TABLE IF EXISTS {table_name}"))
            except Exception as e:
                logger.warning(f"Failed to drop table {table_name}: {e}")

        # 2. Delete registry records (cascading manually)
        if resource_ids:
            try:
                db.query(LinkModel).filter(
                    (LinkModel.source_resource_id.in_(resource_ids)) | 
                    (LinkModel.target_resource_id.in_(resource_ids))
                ).delete(synchronize_session=False)
            except Exception as e:
                logger.warning(f"Failed to delete LinkModel records: {e}")
            
            try:
                from ..registry.translation_model import TranslationModel
                db.query(TranslationModel).filter(
                    TranslationModel.registry_type == 'resource',
                    TranslationModel.registry_id.in_(resource_ids)
                ).delete(synchronize_session=False)
            except Exception as e:
                logger.warning(f"Failed to delete resource translations: {e}")
                
            try:
                db.query(FieldModel).filter(FieldModel.resource_id.in_(resource_ids)).delete(synchronize_session=False)
            except Exception as e:
                logger.warning(f"Failed to delete FieldModel records: {e}")
                
            try:
                db.query(ResourceModel).filter(ResourceModel.app_id == app_db.id).delete(synchronize_session=False)
            except Exception as e:
                logger.warning(f"Failed to delete ResourceModel records: {e}")

        try:
            from ..registry.translation_model import TranslationModel
            db.query(TranslationModel).filter(
                TranslationModel.registry_type == 'app',
                TranslationModel.registry_id == app_db.id
            ).delete(synchronize_session=False)
        except Exception as e:
            logger.warning(f"Failed to delete app translations: {e}")

        try:
            db.query(AppModel).filter(AppModel.id == app_db.id).delete(synchronize_session=False)
            db.commit()
        except Exception as e:
            logger.error(f"Failed to delete AppModel: {e}")
            db.rollback()
            raise e
        logger.info(f"App '{app_name}' purged from database.")

    @classmethod
    def install_from_yaml(cls, yaml_content: str) -> str:
        """Helper to install directly from YAML string."""
        definition = cls.parse_yaml(yaml_content)
        app_name = definition["app"]["name"].lower().replace(" ", "_").replace("-", "_")
        return cls.create_app_scaffold(app_name, definition)

    @classmethod
    def install_from_json(cls, json_content: str) -> str:
        """Helper to install directly from JSON string."""
        definition = cls.parse_json(json_content)
        app_name = definition["app"]["name"].lower().replace(" ", "_").replace("-", "_")
        return cls.create_app_scaffold(app_name, definition)

    @classmethod
    def install_from_zip(cls, zip_bytes: bytes, app_name: Optional[str] = None) -> str:
        """
        Installs an app from a ZIP file containing the Python source.
        If app_name is not provided, it attempts to infer it from the ZIP structure.
        """
        import zipfile
        import io
        import shutil

        apps_root = cls.get_apps_root()
        
        with zipfile.ZipFile(io.BytesIO(zip_bytes)) as z:
            # 1. Infer app name if not provided
            if not app_name:
                # Look for a top-level directory or manifest.py
                top_level = {os.path.dirname(n).split('/')[0] for n in z.namelist() if '/' in n}
                if len(top_level) == 1:
                    app_name = list(top_level)[0]
                else:
                    # Fallback: look for app.py or manifest.py
                    for n in z.namelist():
                        if n.endswith(("app.py", "manifest.py")):
                            app_name = os.path.dirname(n).split('/')[-1] or "new_app"
                            break
            
            if not app_name:
                app_name = "unnamed_app"

            app_path = os.path.join(apps_root, app_name)
            if os.path.exists(app_path):
                raise ValueError(f"App directory already exists: {app_path}")

            # 2. Extract
            z.extractall(apps_root)
            
            # If the zip had a nested folder that isn't exactly 'app_name', we might need to rename it
            # But usually we expect the zip to contain the folder directly.
            
            logger.info(f"App extracted to {app_path}")
            return app_path
